DELETE http://localhost:3003/api/blogs/5ea7582881bdb718501667c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdmlkbHluY2giLCJpZCI6IjVlYTc1ODE4ODFiZGI3MTg1MDE2NjdiZiIsIm5hbWUiOiJEYXZpZCBMeW5jaCIsImlhdCI6MTU4ODE5NTU2MX0.M6DpBBP2oV1v0cgazRxmGF6YVDbwTLmb4E44MStNDQs