PUT http://localhost:3000/carros/5edff08ea464984f7cd3fd5f
Content-Type: application/json

{
  "placa": "def",
  "chassi": "xyz",
  "renavam": "uio",
  "modelo": "X1",
  "marca": "Porsche",
  "ano": "0"
}